### ISSUE TITLE
Rename Glyph Buffers Gn and Gn-1 and Decoded Image Buffers Dn and Dn-1

### ISSUE THREAD

**Issue by palemieux** [w3c/imsc-hrm#54]
... to Glyph Front/Back Buffers and Decoded Image Front/Back Buffers to be consistent with the nomenclature used for the rendering buffers.

**Comment by nigelmegitt** [comment]
This is an important one to do to help with understandability: in my view there's a significant risk that folk will think that image and glyph buffers are caches that last over >2 ISDs, rather than an efficiency measure that applies from one non-empty ISD to the next.

**Comment by nigelmegitt** [comment]
See also https://github.com/w3c/imsc-hrm/pull/55#pullrequestreview-1170818070 - I realised when looking at the pull request that these buffers actually _are_ caches, but that the phrasing around them is a little confusing. Using the terms Front Buffer and Back Buffer for them turned out not to help, because the mode of operation is significantly different to how the composition Front and Back Buffers work.
